### ISSUE TITLE
Dont't support for Vue component (Teleport, Suspense, Transition...)

### ISSUE THREAD

**Issue by hungvx-dev** [unplugin/unplugin-auto-import#426] opened 2023-09-11 04:05 UTC
### Describe the bug

Can't use these components of Vue 3 as: [Teleport](https://vuejs.org/guide/built-ins/teleport.html), Suspense, Transition

<img width="732" alt="image" src="https://github.com/unplugin/unplugin-auto-import/assets/85088954/3ebd925b-8e7a-44db-9641-41b62fb72937">

This is my config,
```
AutoImport({
        eslintrc: {
          enabled: true,
        },
        imports: [
          'vue',
          'vue-router',
          {
            vue: [
              'Teleport',
              'Suspense',
              'Transition',
              'KeepAlive',
            ],
           ...

```

### Reproduction

Vue 3

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 56.38 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.17.0 - ~/.local/share/nvm/v18.17.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.local/share/nvm/v18.17.0/bin/npm
    pnpm: 8.6.12 - ~/.local/share/nvm/v18.17.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-09-11 17:59
I wonder why you need that, they should be supported directly in Vue without importing them.

**Comment by antfu** [comment] 2023-09-11 17:59
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-11 17:59 UTC
