### ISSUE TITLE
Cannot be used directly in vue templates

### ISSUE THREAD

**Issue by eachann1024** [unplugin/unplugin-auto-import#501] opened 2024-05-24 10:58 UTC
### Describe the bug

```html
<el-button
    type="primary" link
    @click="() => {
      createState.form = clone(scope.row)
    }"
  >
  审核
</el-button>
```

![image](https://github.com/unplugin/unplugin-auto-import/assets/43348055/348c5419-7320-49ae-8b86-974f179e8ef2)

![image](https://github.com/unplugin/unplugin-auto-import/assets/43348055/5073c88e-1993-4078-9f9a-ae0a69455e94)

### Reproduction

ok

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12490F
    Memory: 6.99 GB / 31.81 GB
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (124.0.2478.97)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RoadsideParty** [comment] 2024-05-29 06:03
same issue

**Comment by antfu** [comment] 2024-05-29 09:25
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-29 09:25 UTC
