### ISSUE TITLE
In 0.18.0, viteOptimizeDeps was set to true, causing some variables that were previously automatically imported to appear undefined

### ISSUE THREAD

**Issue by laterdayi** [unplugin/unplugin-auto-import#513] opened 2024-07-16 06:53 UTC
### Describe the bug

In 0.18.0, viteOptimizeDeps was set to true, causing some variables that were previously automatically imported to appear undefined

### Reproduction

*

### System Info

```Shell
In 0.18.0, viteOptimizeDeps was set to true, causing some variables that were previously automatically imported to appear undefined
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laterdayi** [comment] 2024-07-16 07:08
![image](https://github.com/user-attachments/assets/294744be-226a-4a5f-bdc9-2da6bbb91fcc)

![image](https://github.com/user-attachments/assets/239d406c-399e-4357-beef-118e19a9adf0)

![image](https://github.com/user-attachments/assets/e4a0b000-a823-4bd7-99c5-dde89feb6946)


Before 0.18.0, it is normal, how should I modify it to make sure it works

**Comment by antfu** [comment] 2024-07-16 10:01
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-16 10:01 UTC
