### ISSUE TITLE
Wildcard import stopped working

### ISSUE THREAD

**Issue by stephanschubert** [unplugin/unplugin-auto-import#471] opened 2024-01-30 19:37 UTC
### Describe the bug

I'm using the Webpack plugin in my Next.js app - my config looks like this:

```
module.exports = {
  defaultExportByFilename: false,
  dirs: [
    "./src/components/**",
    "./src/features/**",
    "./src/hooks/**",
    "./src/lib/**",
  ],
  dts: true,
  eslintrc: {
    enabled: true,
  },
  exclude: [
    /node_modules/,
  ],
  imports: [
    "react",
    // Custom imports
    {
      "date-fns": [["*", "df"]],
      ramda: [["*", "R"]],
    },
  ],
};
```

This worked until a few(?) days ago but now there's an error:

```
   Checking validity of types  ...Failed to compile.

./next.config.js:128:55
Type error: Argument of type '{ defaultExportByFilename: boolean; dirs: string[]; dts: boolean; eslintrc: { enabled: boolean; }; exclude: RegExp[]; imports: (string | { "date-fns": string[][]; ramda: string[][]; })[]; }' is not assignable to parameter of type 'Options'.
  Types of property 'imports' are incompatible.
    Type '(string | { "date-fns": string[][]; ramda: string[][]; })[]' is not assignable to type 'Arrayable<"react" | ImportsMap | "ahooks" | "@vueuse/core" | "@vueuse/math" | "@vueuse/head" | "mobx" | "mobx-react-lite" | "preact" | "quasar" | "react-router" | "react-router-dom" | ... 29 more ... | InlinePreset> | undefined'.
      Type '(string | { "date-fns": string[][]; ramda: string[][]; })[]' is not assignable to type '("react" | ImportsMap | "ahooks" | "@vueuse/core" | "@vueuse/math" | "@vueuse/head" | "mobx" | "mobx-react-lite" | "preact" | "quasar" | "react-router" | "react-router-dom" | ... 29 more ... | InlinePreset)[]'.
        Type 'string | { "date-fns": string[][]; ramda: string[][]; }' is not assignable to type '"react" | ImportsMap | "ahooks" | "@vueuse/core" | "@vueuse/math" | "@vueuse/head" | "mobx" | "mobx-react-lite" | "preact" | "quasar" | "react-router" | "react-router-dom" | ... 29 more ... | InlinePreset'.
          Type 'string' is not assignable to type '"react" | ImportsMap | "ahooks" | "@vueuse/core" | "@vueuse/math" | "@vueuse/head" | "mobx" | "mobx-react-lite" | "preact" | "quasar" | "react-router" | "react-router-dom" | ... 29 more ... | InlinePreset'.

  126 |   ) => {
  127 |     config.plugins.unshift(
> 128 |       require("unplugin-auto-import/webpack").default(autoImportConfig),
      |                                                       ^
  129 |     );
  ```

### Reproduction

Config provided

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.72 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/pnpm/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/Library/pnpm/npm
    pnpm: 7.33.3 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 120.0.6099.234
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-01-31 15:21
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-31 15:21 UTC
