### ISSUE TITLE
自动导入类型会被当做any

### ISSUE THREAD

**Issue by x-wink** [unplugin/unplugin-auto-import#455] opened 2023-12-06 03:39 UTC
### Describe the bug

自动导入只能保证eslint不报错，但是类型信息丢失了
auto import only fix eslint error, but lose the type info
配置：
config:
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/51b547af-7697-4b25-bf59-1477a29c49a2)
自动生成的dts：
auto generated `d.ts` file:
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/cbfd0ebf-f408-4d6f-8d98-2b2aa3ce1464)
ts中类型提示：
type tips in ts:
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/ce4a7c7d-f76a-4571-a343-0ced8b6fc930)
换成手动导入后就正常了
change to manual import it's work normal
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/69249d6c-b3c9-474d-aa4d-8889a0d38b86)

### Reproduction

none

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
    Memory: 15.47 GB / 31.86 GB
  Binaries:
    Node: 18.16.0 - D:\nodejs\node.EXE
    npm: 9.5.1 - D:\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.97)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by x-wink** [comment] 2023-12-06 03:58
好像无法全局导出模块类的类型
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/82a7a77f-77c2-4dc8-a670-9ee457f606bb)
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/a9256972-6ed4-4c90-9792-901b45159c75)
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/93bbe6c4-cec0-427e-b9e6-38944dff0c3d)

**Comment by x-wink** [comment] 2023-12-06 04:02
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/3399194c-4888-4734-b45c-c5e68740e55c)
![image](https://github.com/unplugin/unplugin-auto-import/assets/133745023/2b66ed38-0776-48eb-b201-46a340938d09)

**Comment by x-wink** [comment] 2023-12-06 04:05
只需要在顶层再导出一次类型，全局导出里就不会丢失类型信息了

**Comment by antfu** [comment] 2023-12-06 11:07
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-12-06 11:07 UTC

**Comment by lizyChy0329** [comment] 2024-12-06 02:32
I have the same issus.

Vscode: 1.92.2
Typescript: 5.5.4

![企业微信截图_17334521123221](https://github.com/user-attachments/assets/3f6922f7-f1aa-408b-9ba4-3ab0f24d3da8)

![image](https://github.com/user-attachments/assets/b7c05730-a5bd-4910-b851-b9ed25d44b24)

![image](https://github.com/user-attachments/assets/3799bfe5-fa8e-4659-9350-a3578a62c546)

![image](https://github.com/user-attachments/assets/6fc48237-58f1-4400-92a1-c79cbe11d0ea)
