### ISSUE TITLE
支持 pinia 自动导入支持类型推导

### ISSUE THREAD

**Issue by WangJincheng4869** [unplugin/unplugin-auto-import#477] opened 2024-03-01 02:08 UTC
#### 我开启了 pinia 的自动导入

![image](https://github.com/unplugin/unplugin-auto-import/assets/41162158/36af9261-9ab5-4571-9f3c-333e28aae01d)

#### 但是会出现以下类型错误提示

![image](https://github.com/unplugin/unplugin-auto-import/assets/41162158/08b5c3b8-2766-4e30-b150-199dcbb16989)

#### 直接导入后消失

![image](https://github.com/unplugin/unplugin-auto-import/assets/41162158/b2d0f581-0f00-4b8f-9ba7-d1a52fb672a5)

### Suggested solution

我并不懂这中间发生了什么，导致无法正确的推导类型。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tryforceful** [comment] 2024-03-18 08:21
`defineStore` auto-import works for me with this plugin.

Are you sure that you are importing the generated .d.ts file correctly in your tsconfig?

**Comment by WangJincheng4869** [comment] 2024-03-18 08:29
> `defineStore` auto-import works for me with this plugin. `defineStore` 自动导入对我来说适用于这个插件。
> 
> Are you sure that you are importing the generated .d.ts file correctly in your tsconfig?您确定在 tsconfig 中正确导入生成的 .d.ts 文件吗？

您好！我是这样配置的，应该没有什么问题。
![image](https://github.com/unplugin/unplugin-auto-import/assets/41162158/7973fdfe-114f-404c-874d-4572d0941ca3)

**Comment by antfu** [comment] 2024-03-18 09:09
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-18 09:09 UTC
Labels: enhancement
